// <auto-generated />
namespace Management.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_table_DataInsert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_table_DataInsert));
        
        string IMigrationMetadata.Id
        {
            get { return "202009251417437_add_table_DataInsert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
